version: '3'
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    networks: 
      - backend 
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - "ipfs_data:/data/ipfs"
    command: ["ipfs", "daemon"]
  goapi: 
    build: 
      context: './go-api' 
    environment:
      prod: ${prod}
    networks: 
      - backend 
networks: 
  backend: 
    driver: bridge 
